#!/usr/bin/env bash
# shellcheck shell=bash
# Общие хуки для --persist (FreeBSD/Linux): один маркер в ~/.bashrc, чтобы
# повторные запуски не дублировали блоки.

# Единая строка-маркер; grep -qF по ней.
VPCONFIGURE_BASHRC_HOOK_MARKER='# vpconnect-configure: source persisted env (vp-hook)'

vp_install_bashrc_hook() {
  local env_file=$1
  local bashrc="${HOME:-/root}/.bashrc"
  if [[ -f "$bashrc" ]] && grep -qF "$VPCONFIGURE_BASHRC_HOOK_MARKER" "$bashrc" 2>/dev/null; then
    return 0
  fi
  {
    printf '\n%s\n' "$VPCONFIGURE_BASHRC_HOOK_MARKER"
    printf '[ -r %q ] && . %q\n' "$env_file" "$env_file"
  } >>"$bashrc"
}

vp_install_profile_d_hook() {
  local env_file=$1
  local hook=/etc/profile.d/vpconnect-configure.sh
  [[ -d /etc/profile.d ]] || return 1
  umask 022
  {
    printf '# Generated by vpconnect-configure --persist (login shells)\n'
    printf '[ -r %q ] && . %q\n' "$env_file" "$env_file"
  } >"$hook"
  chmod 644 -- "$hook" 2>/dev/null || true
  return 0
}
